name: Release Security Checks

on:
  workflow_call:
    inputs:
      whitesource_product_name:
        type: string
        required: false
        default: ""
        description: "Whitesource product name"
      whitesource_project_name:
        type: string
        required: false
        default: ""
        description: "Whitesource project name"
      prisma_check:
        type: boolean
        required: false
        default: false
        description: "Run Prisma check"
      sonarqube_hotspot_check:
        type: boolean
        required: false
        default: false
        description: "Run SonarQube Hotspot Check"
    secrets:
      WHITESOURCE_API_KEY:
        description: "Whitesource API key"
        required: false
      MANIFEST_AWS_REGION:
        description: "AWS region for the manifest"
        required: false
      MANIFEST_AWS_ACCESS_KEY_ID:
        description: "AWS access key ID for the manifest"
        required: false
      MANIFEST_AWS_SECRET_ACCESS_KEY:
        description: "AWS secret access key for the manifest"
        required: false
      PRISMA_DOCKER_IMAGE_TO_CHECK:
        description: "Prisma docker image to check"
        required: false
      PRISMA_ACCESS_KEY:
        description: "Prisma access key ID"
        required: false
      PRISMA_ACCESS_KEY_SECRET:
        description: "Prisma secret access key"
        required: false
      SONARQUBE_PROJECT_KEY:
        description: "SonarQube project key"
        required: false
      SONARQUBE_PROJECT_MAIN_BRANCH:
        description: "SonarQube project main branch"
        required: false
      SONARQUBE_QUERY_TOKEN:
        description: "SonarQube query token"
        required: false
      SONARQUBE_HOTSPOTS_API_URL:
        description: "SonarQube hotspots API URL"
        required: false
      FOSSA_API_KEY:
        description: "Fossa API key"
        required: false

permissions:
  contents: read
  checks: write
  pull-requests: read

jobs:
  security-checks:
    name: Security Checks
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0

      - name: FOSSA Guard - Block on Policy Violations
        uses: SolaceDev/solace-public-workflows/.github/actions/fossa-guard@main
        if: github.ref_name == github.event.repository.default_branch
        continue-on-error: true
        with:
          fossa_api_key: ${{ secrets.FOSSA_API_KEY}}
          fossa_project_id: "${{ github.repository_owner }}_${{ github.event.repository.name }}"
          fossa_branch: ${{ github.event.repository.default_branch }}
          fossa_revision: ${{ github.sha }}
          fossa_category: licensing
          fossa_mode: BLOCK
          block_on: policy_conflict

      - name: FOSSA Guard - Block on Security Vulnerabilities
        uses: SolaceDev/solace-public-workflows/.github/actions/fossa-guard@main
        if: github.ref_name == github.event.repository.default_branch
        continue-on-error: true
        with:
          fossa_api_key: ${{ secrets.FOSSA_API_KEY}}
          fossa_project_id: "${{ github.repository_owner }}_${{ github.event.repository.name }}"
          fossa_branch: ${{ github.event.repository.default_branch }}
          fossa_revision: ${{ github.sha }}
          fossa_category: vulnerability
          fossa_mode: BLOCK
          block_on: critical,high

      - name: Run WhiteSource Policy Gate
        if: ${{ inputs.whitesource_product_name != '' && inputs.whitesource_project_name != '' }}
        uses: docker://ghcr.io/solacedev/maas-build-actions:latest
        env:
          WS_API_KEY: ${{ secrets.WHITESOURCE_API_KEY }}
          WS_PRODUCT_NAME: ${{ inputs.whitesource_product_name }}
          WS_PROJECT_NAME: ${{ inputs.whitesource_project_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.MANIFEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MANIFEST_AWS_SECRET_ACCESS_KEY }}
          WS_BLOCKING_POLICY_VIOLATION_LEVELS: "Major,Minor"
          FAIL_IF_POLICY_VIOLATIONS_FOUND: "True"
          AWS_REGION: ${{ secrets.MANIFEST_AWS_REGION }}
          STATUS_CHECK: "True"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ORG: ${{ github.repository_owner }}
          GH_REPO: ${{ github.event.repository.name }}
          GITHUB_SHA: ${{ github.sha }}
        with:
          entrypoint: /bin/sh
          args: >
            -c "
            . $VIRTUAL_ENV/bin/activate &&
            cd $ACTIONS_PATH/whitesource-policy-violation-checker &&
            python whitesource_policy_violation_checker.py
            "

      - name: Run WhiteSource Vulnerability Gate
        if: ${{ inputs.whitesource_product_name != '' && inputs.whitesource_project_name != '' }}
        uses: docker://ghcr.io/solacedev/maas-build-actions:latest
        env:
          WS_API_KEY: ${{ secrets.WHITESOURCE_API_KEY }}
          WS_PRODUCT_NAME: ${{ inputs.whitesource_product_name }}
          WS_PROJECT_NAME: ${{ inputs.whitesource_project_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.MANIFEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MANIFEST_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.MANIFEST_AWS_REGION }}
          WS_JIRA_CHECK: "True"
          JIRA_ONLY: "True"
          STATUS_CHECK: "True"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ORG: ${{ github.repository_owner }}
          GH_REPO: ${{ github.event.repository.name }}
          GITHUB_SHA: ${{ github.sha }}
        with:
          entrypoint: /bin/sh
          args: >
            -c ". $VIRTUAL_ENV/bin/activate &&
            cd $ACTIONS_PATH/whitesource-vulnerability-checker &&
            python whitesource_vulnerability_checker.py
            "

      - name: Run Prisma Check
        if: ${{ fromJson(inputs.prisma_check) }}
        uses: docker://ghcr.io/solacedev/maas-build-actions:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MANIFEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MANIFEST_AWS_SECRET_ACCESS_KEY }}
          PRISMA_REPOSITORY_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE_TO_CHECK: ${{ secrets.PRISMA_DOCKER_IMAGE_TO_CHECK }}
          PRISMA_ACCESS_KEY_ID: ${{ secrets.PRISMA_ACCESS_KEY }}
          PRISMA_ACCESS_KEY_SECRET: ${{ secrets.PRISMA_ACCESS_KEY_SECRET }}
          PRISMA_JIRA_CHECK: "True"
          AWS_REGION: ${{ secrets.MANIFEST_AWS_REGION }}
          JIRA_ONLY: "True"
          STATUS_CHECK: "True"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ORG: ${{ github.repository_owner }}
          GH_REPO: ${{ github.event.repository.name }}
          GITHUB_SHA: ${{ github.sha }}
        with:
          entrypoint: /bin/sh
          args: >
            -c ". $VIRTUAL_ENV/bin/activate &&
            cd $ACTIONS_PATH/prisma-vulnerability-checker &&
            python prisma_vulnerability_checker.py
            "

      - name: Run SonarQube Hotspot Check
        uses: docker://ghcr.io/solacedev/maas-build-actions:latest
        if: ${{ fromJson(inputs.sonarqube_hotspot_check) }}
        env:
          SONARQUBE_PROJECT_KEY: ${{ secrets.SONARQUBE_PROJECT_KEY }}
          SONARQUBE_PROJECT_MAIN_BRANCH: ${{ secrets.SONARQUBE_PROJECT_MAIN_BRANCH }}
          SONARQUBE_QUERY_TOKEN: ${{ secrets.SONARQUBE_QUERY_TOKEN }}
          SONARQUBE_HOTSPOTS_API_URL: ${{ secrets.SONARQUBE_HOTSPOTS_API_URL }}
        with:
          entrypoint: /bin/sh
          args: >
            -c ". $VIRTUAL_ENV/bin/activate &&
            cd $ACTIONS_PATH/sonarqube-hotspot-checker &&
            python sonarqube_checker.py
            "
